/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package froms;

import dataBase.Conexion;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import sockets.*;
import clases.*;

/**
 *
 * @author Alumno
 */
public class DocentesProgramacion extends javax.swing.JFrame {
 static ServerSocket ss;
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    /**
     * Creates new form Docentes
     */
    public DocentesProgramacion() {
        initComponents();
         setSize(1280,720);
        setLocationRelativeTo(null);
        mostrar_grupos();
         l1.setVisible(false);
            jtCalificacion.setVisible(false);
            jcAlumnos.setVisible(false);
            jbGrabar.setVisible(false);
            jbNuevoGrupo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jcGrupos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jcAlumnos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcParcial = new javax.swing.JComboBox<>();
        jtCalificacion = new javax.swing.JTextField();
        jbGrabar = new javax.swing.JButton();
        jbNuevoGrupo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(102, 153, 255));

        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarsesion.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1060, 610, 220, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 60, 850, 550);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventanadocentes.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, -10, 650, 80);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logopequeño.png"))); // NOI18N
        jPanel1.add(jLabel27);
        jLabel27.setBounds(20, 260, 280, 250);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 1280, 700);

        jTabbedPane1.addTab("Principal", jPanel1);

        jPanel3.setLayout(null);

        jcGrupos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        jcGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcGruposActionPerformed(evt);
            }
        });
        jPanel3.add(jcGrupos);
        jcGrupos.setBounds(400, 90, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Grupo.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(280, 80, 130, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materiaProgra.png"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(460, 10, 350, 50);

        l1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Alumnos.png"))); // NOI18N
        jPanel3.add(l1);
        l1.setBounds(310, 160, 170, 40);

        jcAlumnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        jPanel3.add(jcAlumnos);
        jcAlumnos.setBounds(470, 170, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Parcial a evaluar.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(540, 80, 260, 40);

        jcParcial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Primer Parcial", "Segundo Parcial", "Tercer Parcial" }));
        jcParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcParcialActionPerformed(evt);
            }
        });
        jPanel3.add(jcParcial);
        jcParcial.setBounds(800, 90, 140, 30);

        jtCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCalificacionActionPerformed(evt);
            }
        });
        jPanel3.add(jtCalificacion);
        jtCalificacion.setBounds(640, 160, 140, 30);

        jbGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GRABAR CALIFICACIÓN.png"))); // NOI18N
        jbGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrabarActionPerformed(evt);
            }
        });
        jPanel3.add(jbGrabar);
        jbGrabar.setBounds(280, 240, 370, 50);

        jbNuevoGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Evaluar un Nuevo Grupo.png"))); // NOI18N
        jbNuevoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoGrupoActionPerformed(evt);
            }
        });
        jPanel3.add(jbNuevoGrupo);
        jbNuevoGrupo.setBounds(670, 240, 340, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/niño.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(810, 310, 400, 350);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logopequeño.png"))); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(270, 350, 360, 250);

        jButton2.setText("Vizualizar Comentarios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(620, 370, 170, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 0, 1280, 690);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Insertar Calificaciones", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jcGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcGruposActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_jcGruposActionPerformed

    private void jcParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcParcialActionPerformed
        // TODO add your handling code here:
        if (jcParcial.getSelectedItem().equals("Primer Parcial") ||jcParcial.getSelectedItem().equals("Segundo Parcial") ||
            jcParcial.getSelectedItem().equals("Tercer Parcial")) {
            l1.setVisible(true);
            jtCalificacion.setVisible(true);
            jcAlumnos.setVisible(true);
            jbGrabar.setVisible(true);
            jbNuevoGrupo.setVisible(true);
        }
    }//GEN-LAST:event_jcParcialActionPerformed

    private void jtCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCalificacionActionPerformed

    private void jbGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrabarActionPerformed
        // TODO add your handling code here:

        if(jcParcial.getSelectedItem().equals("Primer Parcial")){
            String grupo=String.valueOf(jcGrupos.getSelectedItem());
            String alumno=String.valueOf(jcAlumnos.getSelectedItem());
            String calificacion=jtCalificacion.getText();
            ClaseCalificaciones a=new ClaseCalificaciones(grupo, alumno, calificacion);
            a.agregarPrimer();
            jtCalificacion.setText("");
        }else if (jcParcial.getSelectedItem().equals("Segundo Parcial")) {
            String grupo=String.valueOf(jcGrupos.getSelectedItem());
            String alumno=String.valueOf(jcAlumnos.getSelectedItem());
            String calificacion=jtCalificacion.getText();
            ClaseCalificaciones a=new ClaseCalificaciones(grupo, alumno, calificacion);
            a.agregarSegundo();
            jtCalificacion.setText("");
        }else if (jcParcial.getSelectedItem().equals("Tercer Parcial")){
            String grupo=String.valueOf(jcGrupos.getSelectedItem());
            String alumno=String.valueOf(jcAlumnos.getSelectedItem());
            String calificacion=jtCalificacion.getText();
            ClaseCalificaciones a=new ClaseCalificaciones(grupo, alumno, calificacion);
            a.agregarTercero();
            jtCalificacion.setText("");
        }

    }//GEN-LAST:event_jbGrabarActionPerformed

    private void jbNuevoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoGrupoActionPerformed
        // TODO add your handling code here:
        jcGrupos.setSelectedItem("Selecciona");
        jcParcial.setSelectedItem("Selecciona");

        jtCalificacion.setText("");
        jcAlumnos.removeAllItems();
        jcAlumnos.addItem("Selecciona");
        l1.setVisible(false);
        jtCalificacion.setVisible(false);
        jcAlumnos.setVisible(false);
        jbGrabar.setVisible(false);
        jbNuevoGrupo.setVisible(false);
    }//GEN-LAST:event_jbNuevoGrupoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        chat_server a=new chat_server();
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

     private void cerrarSesion() {
         this.setVisible(false);
        Login logina=new Login();
        logina.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocentesProgramacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocentesProgramacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocentesProgramacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocentesProgramacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocentesProgramacion().setVisible(true);
            }
        });
       
    }
    
    
     private void mostrar_grupos() {
        try{
            Conexion objConexion = new Conexion();
            Statement sentencia=objConexion.getCon().createStatement();//Ejecuta la sentencia
            String sql="Select nombreGrupo from grupos";
            ResultSet registro=sentencia.executeQuery(sql);//Almaceno el resultado de la consulta
            while(registro.next()){
                jcGrupos.addItem(registro.getString(1));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    private void buscar() {
       // ArrayList<Calificaciones> List=new ArrayList();
        
        try{
            Conexion objConexion = new Conexion();
            Statement sentencia=objConexion.getCon().createStatement();//Ejecuta la sentencia
            String sql="select concat(nombre,' ',apellidos) from alumnos where id_grupo="
            + "(select id_grupo from grupos where nombregrupo='"+jcGrupos.getSelectedItem()+"')";
            ResultSet registro=sentencia.executeQuery(sql);//Almaceno el resultado de la consulta
            while(registro.next()){
              jcAlumnos.addItem(registro.getString(1));
            }    
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbGrabar;
    private javax.swing.JButton jbNuevoGrupo;
    private javax.swing.JComboBox<String> jcAlumnos;
    private javax.swing.JComboBox<String> jcGrupos;
    private javax.swing.JComboBox<String> jcParcial;
    private javax.swing.JTextField jtCalificacion;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
