
package froms;

import javax.swing.JOptionPane;
import clases.*;
import static froms.Alumnos.jPanel2;

public class Login extends javax.swing.JFrame {

   
    public Login() {
        initComponents();
        setSize(851, 545);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfUsuarioLogin = new javax.swing.JTextField();
        jpfContraseñaLogin = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        validarlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(jtfUsuarioLogin);
        jtfUsuarioLogin.setBounds(530, 110, 240, 50);
        jPanel1.add(jpfContraseñaLogin);
        jpfContraseñaLogin.setBounds(530, 180, 240, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 90, 230, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contraseña.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 170, 320, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mizton.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 10, 382, 61);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logopequeño.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 260, 310, 230);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ingresar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 250, 280, 80);

        validarlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        jPanel1.add(validarlabel);
        validarlabel.setBounds(0, 0, 850, 540);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(600, 360, 34, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try{
              ClaseLogin obj= new ClaseLogin();//Objeto de la clase Persona
            //int id=Integer.parseInt(jtfId.getText());//Convierto a entero el valor
            String usuario=jtfUsuarioLogin.getText();
            String contraseña=jpfContraseñaLogin.getText();
            obj.setNombreUsuario(usuario);
            obj.setContraseña(contraseña);
            obj.obtenerGrupo();
            String nombre=obj.getNombre();
            obj.obtenerNombre();
            
            System.out.println(obj.obtenerNombre());
            String grup=obj.getGrupo();
//            Alumnos obj1=new Alumnos(nombre);
//            obj1.setNombre1(nombre);
//            obj1.setGrupo1(grup);
//            System.out.println(""+nombre+""+grup);
            obj.iniciarSesionA();//Llamó al método
            String validar=obj.getTipo();
              if (validar==null) {
                   JOptionPane.showMessageDialog(null, "Datos erroneos");  
              }
              if(validar!=null){
                  validarlabel.setText(String.valueOf(obj.getTipo()));
              }
              String tipo=(validarlabel.getText());
        if(tipo.equalsIgnoreCase("alumno")) {
            
           abrirAlumno();
        }else
           if(tipo.equalsIgnoreCase("docente")){
               String usuario2=jtfUsuarioLogin.getText();
               String contrasela2=jpfContraseñaLogin.getText();
               obj.setNombreUsuario(usuario2);
               obj.setContraseña(contrasela2);
               obj.materiaDocente();
               String materia=obj.getMateria();
               if(materia.equalsIgnoreCase("programacion")){
                    this.setVisible(false);
                DocentesProgramacion DocenteP=new DocentesProgramacion();
                DocenteP.setVisible(true);   
               }else if(materia.equalsIgnoreCase("BaseDatos")){
                   this.setVisible(false);
                   DocentesBaseDatos DocenteB=new DocentesBaseDatos();
                DocenteB.setVisible(true); 
               }else if(materia.equalsIgnoreCase("SistemasOperativos")){
               this.setVisible(false);
                   DocentesSistemasOpe DocenteSO=new DocentesSistemasOpe();
                DocenteSO.setVisible(true);
               } 
           }else if(tipo.equalsIgnoreCase("administrador")){
               abrirAdmin();
              }
       } catch(Exception e){
            e.printStackTrace();
        }
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void abrirDocente() {
        this.setVisible(false);
        Docentes Docente=new Docentes();
        Docente.setVisible(true);
    }
    private void abrirAdmin() {
        this.setVisible(false);
        Administrador Administrado=new Administrador();
        Administrado.setVisible(true);
    }
    
    private void abrirAlumno() {
        this.setVisible(false);
        Alumnos Alumno1=new Alumnos();
        Alumno1.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpfContraseñaLogin;
    private javax.swing.JTextField jtfUsuarioLogin;
    private javax.swing.JLabel validarlabel;
    // End of variables declaration//GEN-END:variables
}
